# Roles from ansible-galaxy

- src: geerlingguy.repo-epel
  version: 1.2.3

- src: geerlingguy.mysql
  version: 2.9.2

- src: geerlingguy.apache
  version: 3.0.1

- src: geerlingguy.php
  version: 3.6.1

- src: geerlingguy.nginx
  version: 2.6.0

